-- =========================================================
-- Nova — PostgreSQL schema (portable, standard SQL only)
--
-- Designed to run on ANY PostgreSQL-compatible database:
-- Supabase, Neon, Amazon RDS, a VPS with PostgreSQL, etc.
--
-- Only standard features are used: IDENTITY, JSONB, indexes.
-- Apply with:  npm run db:migrate
-- =========================================================

CREATE TABLE IF NOT EXISTS products (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data       JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_products_cat ON products ((data ->> 'cat'));

CREATE TABLE IF NOT EXISTS orders (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sid        TEXT,
  status     TEXT NOT NULL DEFAULT 'pending',
  product_id INTEGER,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  data       JSONB NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_sid    ON orders (sid);
CREATE INDEX IF NOT EXISTS idx_orders_created ON orders (created_at);

CREATE TABLE IF NOT EXISTS settings (
  key   TEXT PRIMARY KEY,
  value JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_account (
  id         INTEGER PRIMARY KEY CHECK (id = 1),
  code       TEXT NOT NULL,
  pass_salt  TEXT NOT NULL,
  pass_hash  TEXT NOT NULL,
  name       TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Migration bookkeeping for the portable migrate script.
CREATE TABLE IF NOT EXISTS schema_migrations (
  version    INTEGER PRIMARY KEY,
  name       TEXT NOT NULL,
  applied_at TIMESTAMPTZ DEFAULT now()
);