/* =========================================================
   PostgreSQL backend for the Nova database layer.

   Uses only standard PostgreSQL-compatible features:
   - GENERATED BY DEFAULT AS IDENTITY (SQL standard)
   - JSONB document columns for flexible records
   - TIMESTAMPTZ, INDEX, transactions

   No Supabase-specific functionality (RLS, auth.users, etc.).
   The connection string controls everything; swap in any
   PostgreSQL-compatible provider (Supabase, Neon, RDS, a
   self-hosted VPS, …) by changing DATABASE_URL only.
   ========================================================= */

function iso(value) {
  if (!value) return null;
  if (value instanceof Date) return value.toISOString();
  if (typeof value === 'string') return value;
  return new Date(value).toISOString();
}

function rowToProduct(row) {
  const data = (row && row.data) || {};
  return Object.assign({}, data, { id: row.id });
}

function rowToOrder(row) {
  const data = (row && row.data) || {};
  return Object.assign({}, data, {
    id: row.id,
    sid: row.sid,
    status: row.status,
    productId: data.productId != null ? data.productId : row.product_id,
    createdAt: iso(row.created_at),
    updatedAt: iso(row.updated_at),
  });
}

/* =========================================================
   Shared connection setup used by the adapter, migrate.js and
   seed.js. Derives SSL behaviour from ?sslmode= in the URL:
   require/prefer -> encrypt, self-signed chains accepted
   verify-ca/full -> strict certificate verification (add a CA via extra.ca)
   ========================================================= */
function normalizeConnection(connectionString, extra) {
  const extra_ = extra || {};
  let raw = String(connectionString || '');
  let poolConfig = {};
  try {
    const u = new URL(raw);
    const mode = u.searchParams.get('sslmode');
    if (mode && mode !== 'disable') {
      u.searchParams.delete('sslmode');
      raw = u.toString();
      const strict = mode === 'verify-full' || mode === 'verify-ca';
      poolConfig.ssl = strict ? { rejectUnauthorized: true, ca: extra_.ca } : { rejectUnauthorized: false };
    }
  } catch (e) { /* not a URL — leave the raw string untouched */ }
  return Object.assign({ connectionString: raw }, poolConfig);
}

function createAdapter(options) {
  const config = options || {};
  const { Pool } = require('pg');

  const pool = new Pool(Object.assign({
    max: config.max || 10,
    connectionTimeoutMillis: config.connectionTimeoutMillis || 8000,
    idleTimeoutMillis: 30000,
  }, normalizeConnection(config.connectionString, config)));

  const adv = {
    backend: 'postgres',

    async testConnection() {
      const client = await pool.connect();
      try {
        await client.query('SELECT 1');
      } finally {
        client.release();
      }
    },

    async close() {
      await pool.end();
    },

    /* ---------- products ---------- */
    async listProducts() {
      const { rows } = await pool.query('SELECT id, data FROM products ORDER BY id');
      return rows.map(rowToProduct);
    },

    async getProduct(id) {
      const { rows } = await pool.query('SELECT id, data FROM products WHERE id = $1', [Number(id)]);
      return rows.length ? rowToProduct(rows[0]) : null;
    },

    async saveProduct(product) {
      if (product.id == null) {
        const { rows } = await pool.query(
          'INSERT INTO products (data) VALUES ($1) RETURNING id',
          [JSON.stringify(product)]
        );
        return Object.assign({}, product, { id: rows[0].id });
      }
      const id = Number(product.id);
      await pool.query(
        `INSERT INTO products (id, data) VALUES ($1, $2)
         ON CONFLICT (id) DO UPDATE SET data = EXCLUDED.data`,
        [id, JSON.stringify(Object.assign({}, product, { id }))]
      );
      return Object.assign({}, product, { id });
    },

    async deleteProduct(id) {
      const result = await pool.query('DELETE FROM products WHERE id = $1', [Number(id)]);
      return result.rowCount > 0;
    },

    /* ---------- orders ---------- */
    async listOrders() {
      const { rows } = await pool.query('SELECT id, sid, status, created_at, updated_at, product_id, data FROM orders ORDER BY id');
      return rows.map(rowToOrder);
    },

    async findOrderBySid(sid) {
      if (!sid) return null;
      const { rows } = await pool.query(
        'SELECT id, sid, status, created_at, updated_at, product_id, data FROM orders WHERE sid = $1 LIMIT 1',
        [String(sid)]
      );
      return rows.length ? rowToOrder(rows[0]) : null;
    },

    async createOrder(order) {
      const now = iso(order.createdAt) || new Date().toISOString();
      const data = Object.assign({}, order, { createdAt: now, updatedAt: now });
      const by = { sid: data.sid || null, status: data.status || 'pending', created_at: now, updated_at: now, data: JSON.stringify(data) };
      const { rows } = await pool.query(
        `INSERT INTO orders (sid, status, created_at, updated_at, data)
         VALUES ($1, $2, $3, $4, $5) RETURNING id`,
        [by.sid, by.status, by.created_at, by.updated_at, by.data]
      );
      const id = rows[0].id;
      const code = '#' + id;
      const stored = Object.assign({}, data, { id, code });
      await pool.query(
        `UPDATE orders SET data = jsonb_set(data, '{code}', $2) WHERE id = $1`,
        [id, JSON.stringify(code)]
      );
      return stored;
    },

    async updateOrder(id, fullOrder) {
      const now = iso(fullOrder.updatedAt || fullOrder.createdAt) || new Date().toISOString();
      const data = Object.assign({}, fullOrder, {
        id: Number(id),
        updatedAt: now,
        createdAt: iso(fullOrder.createdAt) || now,
      });
      const result = await pool.query(
        `UPDATE orders
         SET sid = $2, status = $3, created_at = $4, updated_at = $5, data = $6
         WHERE id = $1`,
        [Number(id), data.sid || null, data.status || 'pending', data.createdAt, now, JSON.stringify(data)]
      );
      if (result.rowCount === 0) return null;
      return Object.assign({}, data);
    },

    async bulkUpdateOrders(updates) {
      if (!Array.isArray(updates) || !updates.length) return 0;
      const client = await pool.connect();
      let changed = 0;
      try {
        await client.query('BEGIN');
        for (const u of updates) {
          if (!u || u.id == null) continue;
          const id = Number(u.id);
          const { rows } = await client.query(
            'SELECT id, status, updated_at, data FROM orders WHERE id = $1 FOR UPDATE',
            [id]
          );
          if (!rows.length) continue;
          const merged = Object.assign({}, (rows[0].data || {}), u.patch, {
            id,
            updatedAt: new Date().toISOString(),
          });
          const result = await client.query(
            `UPDATE orders SET sid = $2, status = $3, updated_at = $4, data = $5 WHERE id = $1`,
            [id, merged.sid || null, merged.status || 'pending', merged.updatedAt, JSON.stringify(merged)]
          );
          changed += result.rowCount;
        }
        await client.query('COMMIT');
      } catch (e) {
        await client.query('ROLLBACK');
        throw e;
      } finally {
        client.release();
      }
      return changed;
    },

    /* ---------- settings ---------- */
    async getSettings() {
      const { rows } = await pool.query('SELECT key, value FROM settings');
      const out = {};
      for (const r of rows) out[r.key] = r.value;
      return out;
    },

    async saveSettings(obj) {
      const entries = Object.entries(obj || {});
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query('DELETE FROM settings');
        for (const [key, value] of entries) {
          await client.query(
            'INSERT INTO settings (key, value) VALUES ($1, $2)',
            [String(key), JSON.stringify(value)]
          );
        }
        await client.query('COMMIT');
      } catch (e) {
        await client.query('ROLLBACK');
        throw e;
      } finally {
        client.release();
      }
      return obj || {};
    },

    /* ---------- admin account ---------- */
    async hasAdmin() {
      const { rows } = await pool.query('SELECT 1 FROM admin_account WHERE id = 1');
      return rows.length > 0;
    },

    async getAdmin() {
      const { rows } = await pool.query(
        'SELECT id, code, pass_salt, pass_hash, name, created_at FROM admin_account WHERE id = 1'
      );
      if (!rows.length) return null;
      return {
        code: rows[0].code,
        passSalt: rows[0].pass_salt,
        passHash: rows[0].pass_hash,
        name: rows[0].name || '',
        createdAt: iso(rows[0].created_at),
      };
    },

    async saveAdmin(admin) {
      await pool.query(
        `INSERT INTO admin_account (id, code, pass_salt, pass_hash, name, created_at)
         VALUES (1, $1, $2, $3, $4, $5)
         ON CONFLICT (id) DO UPDATE
           SET code = EXCLUDED.code,
               pass_salt = EXCLUDED.pass_salt,
               pass_hash = EXCLUDED.pass_hash,
               name = EXCLUDED.name,
               created_at = EXCLUDED.created_at`,
        [
          String(admin.code || ''),
          String(admin.passSalt || ''),
          String(admin.passHash || ''),
          String(admin.name || ''),
          iso(admin.createdAt) || new Date().toISOString(),
        ]
      );
      return admin;
    },
  };

  return adv;
}

module.exports = { createAdapter, normalizeConnection };